Make TEST_ALERT fail if an error occurs in the alert script and allow 	it to add a detailed error message to the response.
	* src/alert_methods/SCP/alert: Write error messages to stderr in
	addition to logger.

	* src/alert_methods/Send/alert: Exit with the same exit code as socat.

	* src/alert_methods/SMB/alert: Exit with code from smbclient and output
	messages to stderr.

	* src/alert_methods/SNMP/alert: Output exit code and stderr text to
	stderr.

	* src/alert_methods/Sourcefire/alert: Exit with code from connector.

	* src/alert_methods/verinice/alert: Exit with code from connector.

	* src/gmp.c (gmp_xml_handle_end_element): In CLIENT_TEST_ALERT case,
	handle new manage_test_alert return code for failed alert script.

	* src/manage.h (manage_alert, manage_test_alert): Add new parameter.

	* src/manage_sql.c (run_alert_script): Fail with a special return code
	if the script ends with a non-zero exit code and add new message output
	parameter. Remove temporary files on error.
	(snmp_to_host, send_to_host, scp_to_host, smb_send_to_host)
	(escalate_2, manage_alert, escalate_1, manage_test_alert):  Add new 
	script_message output parameter.
	(event, manage_send_report): Add param for escalate function calls.

	* src/schema_formats/XML/GMP.xml.in: Add new status_details element
	to test_alert command.

git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/gvm@30043 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/src/alert_methods/SCP/alert b/src/alert_methods/SCP/alert
--- a/src/alert_methods/SCP/alert
+++ b/src/alert_methods/SCP/alert
@@ -37,32 +37,42 @@ echo $KNOWN_HOSTS > $KNOWN_HOSTS_FILE
 PASSWORD_FILE=`mktemp` || exit 1
 echo $PASSWORD > $PASSWORD_FILE
 
+log_error() {
+  logger "SCP alert: $1"
+  echo "$1" >&2
+}
+
 # Escape destination twice because it is also expanded on the remote end.
-sshpass -f ${PASSWORD_FILE} scp -o HashKnownHosts=no -o UserKnownHostsFile="${KNOWN_HOSTS_FILE} ~/.ssh/known_hosts ~/.ssh/known_hosts2 /etc/ssh/ssh_known_hosts" "${REPORT_FILE}" "${USERNAME}@${HOST}:'${DEST}'"
+sshpass -f ${PASSWORD_FILE} scp -o HashKnownHosts=no -o UserKnownHostsFile="${KNOWN_HOSTS_FILE} ~/.ssh/known_hosts ~/.ssh/known_hosts2 /etc/ssh/ssh_known_hosts" "${REPORT_FILE}" "${USERNAME}@${HOST}:'${DEST}'" 2>/dev/null
 
 EXIT_CODE=$?
 if [ $EXIT_CODE -eq 1 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}: Invalid command line argument"
+  log_error "sshpass failed with exit code ${EXIT_CODE}: Invalid command line argument"
 elif [ $EXIT_CODE -eq 2 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}: Conflicting arguments given"
+  log_error "sshpass failed with exit code ${EXIT_CODE}: Conflicting arguments given"
 elif [ $EXIT_CODE -eq 3 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}: General runtime error"
+  log_error "sshpass failed with exit code ${EXIT_CODE}: General runtime error"
 elif [ $EXIT_CODE -eq 4 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}: Unrecognized response from ssh (parse error)"
+  log_error "sshpass failed with exit code ${EXIT_CODE}: Unrecognized response from ssh (parse error)"
 elif [ $EXIT_CODE -eq 5 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}: Invalid/incorrect password"
+  log_error "sshpass failed with exit code ${EXIT_CODE}: Invalid/incorrect password"
 elif [ $EXIT_CODE -eq 6 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}: Host public key is unknown."
+  log_error "sshpass failed with exit code ${EXIT_CODE}: Host public key is unknown."
+elif [ $EXIT_CODE -eq 127 ]
+then
+  log_error "sshpass failed with exit code ${EXIT_CODE}: Command not found."
 elif [ $EXIT_CODE -ne 0 ]
 then
-  logger "SCP alert: sshpass failed with exit code ${EXIT_CODE}"
+  log_error "sshpass failed with exit code ${EXIT_CODE}"
 fi
 
 rm $KNOWN_HOSTS_FILE
 rm $PASSWORD_FILE
+
+exit $EXIT_CODE
