Prepare sync scripts for combining them into one
This changes the CERT and SCAP sync scripts so they are essentially the
same except for the feed names, URLs and paths.
Also, some initializations have been moved around so they can be run
after parsing the arguments so a type argument can be added to the
generic script later.

diff --git a/tools/greenbone-certdata-sync.in b/tools/greenbone-certdata-sync.in
--- a/tools/greenbone-certdata-sync.in
+++ b/tools/greenbone-certdata-sync.in
@@ -17,7 +17,7 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # This script synchronizes a GVM installation with the
-# CERT data from either the Greenbone Security Feed (in
+# feed data from either the Greenbone Security Feed (in
 # case a GSF access key is present) or else from the Greenbone
 # Community Feed.
 
@@ -29,7 +29,7 @@ log_notice () {
 ########## SETTINGS
 ########## ========
 
-# PRIVATE_SUBDIR defines a subdirectory of the CERT data directory
+# PRIVATE_SUBDIR defines a subdirectory of the feed data directory
 # where files not part of the feed or database will not be deleted by rsync.
 if [ -z "$PRIVATE_SUBDIR" ]
 then
@@ -39,8 +39,8 @@ fi
 # RSYNC_DELETE controls whether files which are not part of the repository will
 # be removed from the local directory after synchronization. The default value
 # for this setting is
-# "--delete --exclude cert.db --exclude $PRIVATE_SUBDIR/",
-# which means that files which are not part of the feed, database or private
+# "--delete --exclude feed.xml --exclude $PRIVATE_SUBDIR/",
+# which means that files which are not part of the feed, feed info or private
 # directory will be deleted.
 RSYNC_DELETE="--delete --exclude feed.xml --exclude \"$PRIVATE_SUBDIR/\""
 
@@ -71,20 +71,17 @@ then
   LOCK_FILE="@GVM_FEED_LOCK_PATH@"
 fi
 
+
 ########## GLOBAL VARIABLES
 ########## ================
 
 VERSION=@GVMD_VERSION@
 
-[ -r "@GVM_SYSCONF_DIR@/greenbone-certdata-sync.conf" ] && . "@GVM_SYSCONF_DIR@/greenbone-certdata-sync.conf"
-
-CERT_DIR="@GVM_CERT_DATA_DIR@"
+[ -r "@GVM_SYSCONF_DIR@/greenbone-feed-sync.conf" ] && . "@GVM_SYSCONF_DIR@/greenbone-feed-sync.conf"
 
 if [ -z "$DROP_USER" ]; then
   DROP_USER="@GVM_DEFAULT_DROP_USER@"
 fi
-
-TIMESTAMP="$CERT_DIR/timestamp"
 
 ACCESSKEY="@GVM_ACCESS_KEY_DIR@/gsf-access-key"
 
@@ -108,10 +105,6 @@ if [ -e $ACCESSKEY ]
 then
   RESTRICTED=1
 
-  if [ -z "$FEED_NAME" ] ; then
-    FEED_NAME="Greenbone CERT Feed"
-  fi
-
   if [ -z "$FEED_VENDOR" ] ; then
     FEED_VENDOR="Greenbone Networks GmbH"
   fi
@@ -123,22 +116,12 @@ then
 else
   RESTRICTED=0
 
-  if [ -z "$FEED_NAME" ] ; then
-    FEED_NAME="Greenbone Community CERT Feed"
-  fi
-
   if [ -z "$FEED_VENDOR" ] ; then
     FEED_VENDOR="Greenbone Networks GmbH"
   fi
 
   if [ -z "$FEED_HOME" ] ; then
     FEED_HOME="https://community.greenbone.net/t/about-greenbone-community-feed-gcf/1224"
-  fi
-
-  if [ -z "$COMMUNITY_CERT_RSYNC_FEED" ]; then
-    COMMUNITY_CERT_RSYNC_FEED=rsync://feed.community.greenbone.net:/cert-data
-    # An alternative syntax which might work if the above doesn't:
-    # COMMUNITY_CERT_RSYNC_FEED=rsync@feed.community.greenbone.net::cert-data
   fi
 
 fi
@@ -165,6 +148,42 @@ log_err () {
   $LOG_CMD -p daemon.err "$1"
 }
 
+init_feed_type () {
+  if [ "CERT" = "$FEED_TYPE" ]
+  then
+    [ -r "@GVM_SYSCONF_DIR@/greenbone-certdata-sync.conf" ] && . "@GVM_SYSCONF_DIR@/greenbone-certdata-sync.conf"
+
+    FEED_TYPE_LONG="CERT data"
+    FEED_DIR="@GVM_CERT_DATA_DIR@"
+    TIMESTAMP="$FEED_DIR/timestamp"
+    SCRIPT_ID="CERTSYNC"
+
+    if [ -z "$COMMUNITY_CERT_RSYNC_FEED" ]; then
+      COMMUNITY_RSYNC_FEED="rsync://feed.community.greenbone.net:/cert-data"
+      # An alternative syntax which might work if the above doesn't:
+      # COMMUNITY_RSYNC_FEED="rsync@feed.community.greenbone.net::cert-data"
+    else
+      COMMUNITY_RSYNC_FEED="$COMMUNITY_CERT_RSYNC_FEED"
+    fi
+
+    GSF_RSYNC_PATH="/cert-data"
+
+    if [ -e $ACCESSKEY ] ; then
+      if [ -z "$FEED_NAME" ] ; then
+        FEED_NAME="Greenbone CERT Feed"
+      fi
+    else
+      if [ -z "$FEED_NAME" ] ; then
+        FEED_NAME="Greenbone Community CERT Feed"
+      fi
+    fi
+  else
+    echo "Invalid feed type $FEED_TYPE"
+    log_err "Invalid feed type $FEED_TYPE"
+    exit 1
+  fi
+}
+
 write_feed_xml () {
   if [ -r $TIMESTAMP ]
   then
@@ -173,19 +192,19 @@ write_feed_xml () {
     FEED_VERSION=0
   fi
 
-  mkdir -p $CERT_DIR
-  echo '<feed id="6315d194-4b6a-11e7-a570-28d24461215b">' > $CERT_DIR/feed.xml
-  echo "<type>CERT</type>" >> $CERT_DIR/feed.xml
-  echo "<name>$FEED_NAME</name>" >> $CERT_DIR/feed.xml
-  echo "<version>$FEED_VERSION</version>" >> $CERT_DIR/feed.xml
-  echo "<vendor>$FEED_VENDOR</vendor>" >> $CERT_DIR/feed.xml
-  echo "<home>$FEED_HOME</home>" >> $CERT_DIR/feed.xml
-  echo "<description>" >> $CERT_DIR/feed.xml
-  echo "This script synchronizes a CERT collection with the '$FEED_NAME'." >> $CERT_DIR/feed.xml
-  echo "The '$FEED_NAME' is provided by '$FEED_VENDOR'." >> $CERT_DIR/feed.xml
-  echo "Online information about this feed: '$FEED_HOME'." >> $CERT_DIR/feed.xml
-  echo "</description>" >> $CERT_DIR/feed.xml
-  echo "</feed>" >> $CERT_DIR/feed.xml
+  mkdir -p $FEED_DIR
+  echo '<feed id="6315d194-4b6a-11e7-a570-28d24461215b">' > $FEED_DIR/feed.xml
+  echo "<type>$FEED_TYPE</type>" >> $FEED_DIR/feed.xml
+  echo "<name>$FEED_NAME</name>" >> $FEED_DIR/feed.xml
+  echo "<version>$FEED_VERSION</version>" >> $FEED_DIR/feed.xml
+  echo "<vendor>$FEED_VENDOR</vendor>" >> $FEED_DIR/feed.xml
+  echo "<home>$FEED_HOME</home>" >> $FEED_DIR/feed.xml
+  echo "<description>" >> $FEED_DIR/feed.xml
+  echo "This script synchronizes a $FEED_TYPE collection with the '$FEED_NAME'." >> $FEED_DIR/feed.xml
+  echo "The '$FEED_NAME' is provided by '$FEED_VENDOR'." >> $FEED_DIR/feed.xml
+  echo "Online information about this feed: '$FEED_HOME'." >> $FEED_DIR/feed.xml
+  echo "</description>" >> $FEED_DIR/feed.xml
+  echo "</feed>" >> $FEED_DIR/feed.xml
 }
 
 create_tmp_key () {
@@ -199,8 +218,16 @@ remove_tmp_key () {
   rm -rf "$KEYTEMPDIR"
 }
 
+set_interrupt_trap () {
+  trap "handle_interrupt $1" 2
+}
+
+handle_interrupt () {
+  echo "$1:X" >&3
+}
+
 do_describe () {
-  echo "This script synchronizes a CERT collection with the '$FEED_NAME'."
+  echo "This script synchronizes a $FEED_TYPE collection with the '$FEED_NAME'."
   echo "The '$FEED_NAME' is provided by '$FEED_VENDOR'."
   echo "Online information about this feed: '$FEED_HOME'."
 }
@@ -216,15 +243,15 @@ do_feedversion () {
 # If gos-state-manager is missing the settings values can not be retrieved.
 #
 # Input: option
-# Output: value as string or empty String if gos-state-manager is missing
+# Output: value as string or empty String if gos-state-manager is not installed
 #         or option not set
 get_value ()
 {
   value=""
   key=$1
-  if which gos-state-manager >/dev/null 2>&1
+  if which gos-state-manager 1>/dev/null 2>&1
   then
-    if gos-state-manager get "$key.value" >/dev/null 2>&1
+    if gos-state-manager get "$key.value" 1>/dev/null 2>&1
     then
       value="$(gos-state-manager get "$key.value")"
     fi
@@ -254,11 +281,10 @@ is_feed_current () {
 
     if [ -z "$feeduser" ] || [ -z "$custid_at_host" ]
     then
-      log_err "CERT synchronization: Could not determine credentials, aborting synchronization."
+      log_err "Could not determine credentials, aborting synchronization."
       rm -rf "$FEED_INFO_TEMP_DIR"
       exit 1
     fi
-    echo "custid_at_host = '$custid_at_host'"
 
     gsmproxy=$(get_value proxy_feed | sed -r -e 's/^.*\/\///' -e 's/:([0-9]+)$/ \1/')
     syncport=$(get_value syncport)
@@ -278,7 +304,7 @@ is_feed_current () {
       fi
     fi
     create_tmp_key
-    rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $TMPACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:/cert-data/timestamp "$FEED_INFO_TEMP_DIR"
+    rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $TMPACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:$GSF_RSYNC_PATH/timestamp "$FEED_INFO_TEMP_DIR"
     if [ $? -ne 0 ]
     then
       log_err "rsync failed, aborting synchronization."
@@ -289,7 +315,7 @@ is_feed_current () {
     remove_tmp_key
   else
     log_notice "No Greenbone Security Feed access key found, falling back to Greenbone Community Feed"
-    eval "$RSYNC -ltvrP \"$COMMUNITY_CERT_RSYNC_FEED/timestamp\" \"$FEED_INFO_TEMP_DIR\""
+    eval "$RSYNC -ltvrP \"$COMMUNITY_RSYNC_FEED/timestamp\" \"$FEED_INFO_TEMP_DIR\""
     if [ $? -ne 0 ]
     then
       log_err "rsync failed, aborting synchronization."
@@ -298,7 +324,7 @@ is_feed_current () {
     fi
   fi
 
-  FEED_VERSION_SERVER=`cat $FEED_INFO_TEMP_DIR/timestamp`
+  FEED_VERSION_SERVER=`cat "$FEED_INFO_TEMP_DIR/timestamp"`
 
   if [ -z "$FEED_VERSION_SERVER" ]
   then
@@ -321,7 +347,7 @@ is_feed_current () {
 }
 
 do_help () {
-  echo "$0: Sync CERT data"
+  echo "$0: Sync feed data"
 
   if [ -e $ACCESSKEY ]
   then
@@ -330,12 +356,12 @@ do_help () {
     echo "No GSF access key found: Using Community Feed"
   fi
 
-  echo " --describe     display current feed info"
-  echo " --feedversion  display version of this feed"
-  echo " --help         display this help"
-  echo " --identify     display information"
-  echo " --selftest     perform self-test"
-  echo " --version      display version"
+  echo " --describe        display current feed info"
+  echo " --feedversion     display version of this feed"
+  echo " --help            display this help"
+  echo " --identify        display information"
+  echo " --selftest        perform self-test"
+  echo " --version         display version"
   echo ""
   exit 0
 }
@@ -345,11 +371,11 @@ do_rsync_community_feed () {
     log_err "rsync not found!"
   else
     log_notice "Using rsync: $RSYNC"
-    log_notice "Configured CERT data rsync feed: $COMMUNITY_CERT_RSYNC_FEED"
-    mkdir -p "$CERT_DIR"
-    eval "$RSYNC -ltvrP $RSYNC_DELETE \"$COMMUNITY_CERT_RSYNC_FEED\" \"$CERT_DIR\""
+    log_notice "Configured $FEED_TYPE_LONG rsync feed: $COMMUNITY_RSYNC_FEED"
+    mkdir -p "$FEED_DIR"
+    eval "$RSYNC -ltvrP $RSYNC_DELETE \"$COMMUNITY_RSYNC_FEED\" \"$FEED_DIR\""
     if [ $? -ne 0 ] ; then
-      log_err "rsync failed. Your CERT data might be broken now."
+      log_err "rsync failed. Your $FEED_TYPE_LONG might be broken now."
       exit 1
     fi
   fi
@@ -366,22 +392,23 @@ do_sync_community_feed () {
   fi
 }
 
-sync_certdata(){
+sync_feed_data(){
   if [ -e $ACCESSKEY ]
   then
-    log_notice "Found Greenbone Security Feed subscription file, trying to synchronize with Greenbone CERT data Repository ..."
+    log_notice "Found Greenbone Security Feed subscription file, trying to synchronize with Greenbone $FEED_TYPE_LONG Repository ..."
     notsynced=1
 
-    mkdir -p "$CERT_DIR"
+    mkdir -p "$FEED_DIR"
     read feeduser < $ACCESSKEY
     custid_at_host=`head -1 $ACCESSKEY | cut -d : -f 1`
+
     if [ -z "$feeduser" ] || [ -z "$custid_at_host" ]
     then
       log_err "Could not determine credentials, aborting synchronization."
       exit 1
     fi
 
-    while [ 1 -eq $notsynced ]
+    while [ 0 -ne "$notsynced" ]
     do
 
       gsmproxy=$(get_value proxy_feed | sed -r -e 's/^.*\/\///' -e 's/:([0-9]+)$/ \1/')
@@ -402,7 +429,7 @@ sync_certdata(){
         fi
       fi
       create_tmp_key
-      rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $ACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:/cert-data/ $CERT_DIR
+      rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $ACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:$GSF_RSYNC_PATH/ $FEED_DIR
       if [ 0 -ne "$?" ] ; then
         log_err "rsync failed, aborting synchronization."
         remove_tmp_key
@@ -411,8 +438,7 @@ sync_certdata(){
       remove_tmp_key
       notsynced=0
     done
-    log_notice "Synchronization with the Greenbone CERT data Repository successful."
-    echo
+    log_notice "Synchronization with the Greenbone $FEED_TYPE_LONG Repository successful."
   else
     log_notice "No Greenbone Security Feed access key found, falling back to Greenbone Community Feed"
     do_sync_community_feed
@@ -442,43 +468,55 @@ do_self_test () {
 ########## START
 ########## =====
 
+while test $# -gt 0; do
+  case "$1" in
+    "--version"|"--identify"|"--describe"|"--feedversion"|"--help"|"--selftest"|"--feedcurrent")
+      if [ -z "$ACTION" ] ; then
+        ACTION="$1"
+      fi
+      ;;
+  esac
+  shift
+done
+
+FEED_TYPE="CERT"
+
+init_feed_type
+
 write_feed_xml
 
-while test $# -gt 0; do
- case "$1" in
-        --version)
-          echo $VERSION
-          exit 0
-           ;;
-        --identify)
-          echo "CERTSYNC|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|CERTSYNC"
-          exit 0
-          ;;
-        --describe)
-          do_describe
-          exit 0
-          ;;
-        --feedversion)
-          do_feedversion
-          exit 0
-          ;;
-        --help)
-          do_help
-          exit 0
-          ;;
-        --selftest)
-          SELFTEST_FAIL=0
-          SELFTEST_STDERR=1
-          do_self_test
-          exit $SELFTEST_FAIL
-          ;;
-        --feedcurrent)
-          is_feed_current
-          exit $?
-          ;;
-      esac
-      shift
-done
+case "$ACTION" in
+  --version)
+    echo $VERSION
+    exit 0
+    ;;
+  --identify)
+    echo "$SCRIPT_ID|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|$SCRIPT_ID"
+    exit 0
+    ;;
+  --describe)
+    do_describe
+    exit 0
+    ;;
+  --feedversion)
+    do_feedversion
+    exit 0
+    ;;
+  --help)
+    do_help
+    exit 0
+    ;;
+  --selftest)
+    SELFTEST_FAIL=0
+    SELFTEST_STDERR=1
+    do_self_test
+    exit $SELFTEST_FAIL
+    ;;
+  --feedcurrent)
+    is_feed_current
+    exit $?
+    ;;
+esac
 
 SELFTEST_FAIL=0
 do_self_test
@@ -500,7 +538,7 @@ fi
     exit 1
   fi
   date > $LOCK_FILE
-  sync_certdata
+  sync_feed_data
   echo -n > $LOCK_FILE
 ) 9>$LOCK_FILE
 
