Prepare sync scripts for combining them into one
This changes the CERT and SCAP sync scripts so they are essentially the
same except for the feed names, URLs and paths.
Also, some initializations have been moved around so they can be run
after parsing the arguments so a type argument can be added to the
generic script later.

diff --git a/tools/greenbone-scapdata-sync.in b/tools/greenbone-scapdata-sync.in
--- a/tools/greenbone-scapdata-sync.in
+++ b/tools/greenbone-scapdata-sync.in
@@ -17,7 +17,7 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # This script synchronizes a GVM installation with the
-# SCAP data from either the Greenbone Security Feed (in
+# feed data from either the Greenbone Security Feed (in
 # case a GSF access key is present) or else from the Greenbone
 # Community Feed.
 
@@ -29,7 +29,7 @@ log_notice () {
 ########## SETTINGS
 ########## ========
 
-# PRIVATE_SUBDIR defines a subdirectory of the SCAP data directory
+# PRIVATE_SUBDIR defines a subdirectory of the feed data directory
 # where files not part of the feed or database will not be deleted by rsync.
 if [ -z "$PRIVATE_SUBDIR" ]
 then
@@ -39,8 +39,8 @@ fi
 # RSYNC_DELETE controls whether files which are not part of the repository will
 # be removed from the local directory after synchronization. The default value
 # for this setting is
-# "--delete --exclude scap.db --exclude $PRIVATE_SUBDIR/",
-# which means that files which are not part of the feed, database or private
+# "--delete --exclude feed.xml --exclude $PRIVATE_SUBDIR/",
+# which means that files which are not part of the feed, feed info or private
 # directory will be deleted.
 RSYNC_DELETE="--delete --exclude feed.xml --exclude \"$PRIVATE_SUBDIR/\""
 
@@ -57,10 +57,6 @@ RSYNC_COMPRESS="--compress-level=9"
 # doing.
 PORT=24
 
-# Setting this to 1 enables verbose mode, which outputs additional data.
-# This is usually done with the option --verbose
-VERBOSE=0
-
 # SCRIPT_NAME is the name the scripts will use to identify itself and to mark
 # log messages.
 SCRIPT_NAME="greenbone-scapdata-sync"
@@ -70,7 +66,7 @@ SCRIPT_NAME="greenbone-scapdata-sync"
 LOG_CMD="logger -t $SCRIPT_NAME"
 
 # LOCK_FILE is the name of the file used to lock the feed during sync or update.
-if [ -z LOCK_FILE ]
+if [ -z "$LOCK_FILE" ]
 then
   LOCK_FILE="@GVM_FEED_LOCK_PATH@"
 fi
@@ -81,15 +77,11 @@ fi
 
 VERSION=@GVMD_VERSION@
 
-[ -r @GVM_SYSCONF_DIR@/greenbone-scapdata-sync.conf ] && . @GVM_SYSCONF_DIR@/greenbone-scapdata-sync.conf
-
-SCAP_DIR="@GVM_SCAP_DATA_DIR@"
+[ -r "@GVM_SYSCONF_DIR@/greenbone-feed-sync.conf" ] && . "@GVM_SYSCONF_DIR@/greenbone-feed-sync.conf"
 
 if [ -z "$DROP_USER" ]; then
   DROP_USER="@GVM_DEFAULT_DROP_USER@"
 fi
-
-TIMESTAMP="$SCAP_DIR/timestamp"
 
 ACCESSKEY="@GVM_ACCESS_KEY_DIR@/gsf-access-key"
 
@@ -113,10 +105,6 @@ if [ -e $ACCESSKEY ]
 then
   RESTRICTED=1
 
-  if [ -z "$FEED_NAME" ] ; then
-    FEED_NAME="Greenbone SCAP Feed"
-  fi
-
   if [ -z "$FEED_VENDOR" ] ; then
     FEED_VENDOR="Greenbone Networks GmbH"
   fi
@@ -128,22 +116,12 @@ then
 else
   RESTRICTED=0
 
-  if [ -z "$FEED_NAME" ] ; then
-    FEED_NAME="Greenbone Community SCAP Feed"
-  fi
-
   if [ -z "$FEED_VENDOR" ] ; then
     FEED_VENDOR="Greenbone Networks GmbH"
   fi
 
   if [ -z "$FEED_HOME" ] ; then
     FEED_HOME="https://community.greenbone.net/t/about-greenbone-community-feed-gcf/1224"
-  fi
-
-  if [ -z "$COMMUNITY_SCAP_RSYNC_FEED" ]; then
-    COMMUNITY_SCAP_RSYNC_FEED=rsync://feed.community.greenbone.net:/scap-data
-    # An alternative syntax which might work if the above doesn't:
-    # COMMUNITY_SCAP_RSYNC_FEED=rsync@feed.community.greenbone.net::scap-data
   fi
 
 fi
@@ -170,6 +148,42 @@ log_err () {
   $LOG_CMD -p daemon.err "$1"
 }
 
+init_feed_type () {
+  if [ "SCAP" = "$FEED_TYPE" ]
+  then
+    [ -r "@GVM_SYSCONF_DIR@/greenbone-scapdata-sync.conf" ] && . "@GVM_SYSCONF_DIR@/greenbone-scapdata-sync.conf"
+
+    FEED_TYPE_LONG="SCAP data"
+    FEED_DIR="@GVM_SCAP_DATA_DIR@"
+    TIMESTAMP="$FEED_DIR/timestamp"
+    SCRIPT_ID="SCAPSYNC"
+
+    if [ -z "$COMMUNITY_SCAP_RSYNC_FEED" ]; then
+      COMMUNITY_RSYNC_FEED="rsync://feed.community.greenbone.net:/scap-data"
+      # An alternative syntax which might work if the above doesn't:
+      # COMMUNITY_RSYNC_FEED="rsync@feed.community.greenbone.net::scap-data"
+    else
+      COMMUNITY_RSYNC_FEED="$COMMUNITY_SCAP_RSYNC_FEED"
+    fi
+
+    GSF_RSYNC_PATH="/scap-data"
+
+    if [ -e $ACCESSKEY ] ; then
+      if [ -z "$FEED_NAME" ] ; then
+        FEED_NAME="Greenbone SCAP Feed"
+      fi
+    else
+      if [ -z "$FEED_NAME" ] ; then
+        FEED_NAME="Greenbone Community SCAP Feed"
+      fi
+    fi
+  else
+    echo "Invalid feed type $FEED_TYPE"
+    log_err "Invalid feed type $FEED_TYPE"
+    exit 1
+  fi
+}
+
 write_feed_xml () {
   if [ -r $TIMESTAMP ]
   then
@@ -178,19 +192,19 @@ write_feed_xml () {
     FEED_VERSION=0
   fi
 
-  mkdir -p $SCAP_DIR
-  echo '<feed id="6315d194-4b6a-11e7-a570-28d24461215b">' > $SCAP_DIR/feed.xml
-  echo "<type>SCAP</type>" >> $SCAP_DIR/feed.xml
-  echo "<name>$FEED_NAME</name>" >> $SCAP_DIR/feed.xml
-  echo "<version>$FEED_VERSION</version>" >> $SCAP_DIR/feed.xml
-  echo "<vendor>$FEED_VENDOR</vendor>" >> $SCAP_DIR/feed.xml
-  echo "<home>$FEED_HOME</home>" >> $SCAP_DIR/feed.xml
-  echo "<description>" >> $SCAP_DIR/feed.xml
-  echo "This script synchronizes a SCAP collection with the '$FEED_NAME'." >> $SCAP_DIR/feed.xml
-  echo "The '$FEED_NAME' is provided by '$FEED_VENDOR'." >> $SCAP_DIR/feed.xml
-  echo "Online information about this feed: '$FEED_HOME'." >> $SCAP_DIR/feed.xml
-  echo "</description>" >> $SCAP_DIR/feed.xml
-  echo "</feed>" >> $SCAP_DIR/feed.xml
+  mkdir -p $FEED_DIR
+  echo '<feed id="6315d194-4b6a-11e7-a570-28d24461215b">' > $FEED_DIR/feed.xml
+  echo "<type>$FEED_TYPE</type>" >> $FEED_DIR/feed.xml
+  echo "<name>$FEED_NAME</name>" >> $FEED_DIR/feed.xml
+  echo "<version>$FEED_VERSION</version>" >> $FEED_DIR/feed.xml
+  echo "<vendor>$FEED_VENDOR</vendor>" >> $FEED_DIR/feed.xml
+  echo "<home>$FEED_HOME</home>" >> $FEED_DIR/feed.xml
+  echo "<description>" >> $FEED_DIR/feed.xml
+  echo "This script synchronizes a $FEED_TYPE collection with the '$FEED_NAME'." >> $FEED_DIR/feed.xml
+  echo "The '$FEED_NAME' is provided by '$FEED_VENDOR'." >> $FEED_DIR/feed.xml
+  echo "Online information about this feed: '$FEED_HOME'." >> $FEED_DIR/feed.xml
+  echo "</description>" >> $FEED_DIR/feed.xml
+  echo "</feed>" >> $FEED_DIR/feed.xml
 }
 
 create_tmp_key () {
@@ -213,7 +227,7 @@ handle_interrupt () {
 }
 
 do_describe () {
-  echo "This script synchronizes a SCAP collection with the '$FEED_NAME'."
+  echo "This script synchronizes a $FEED_TYPE collection with the '$FEED_NAME'."
   echo "The '$FEED_NAME' is provided by '$FEED_VENDOR'."
   echo "Online information about this feed: '$FEED_HOME'."
 }
@@ -264,10 +278,11 @@ is_feed_current () {
   then
     read feeduser < $ACCESSKEY
     custid_at_host=`head -1 $ACCESSKEY | cut -d : -f 1`
-    if [ -z $feeduser ] || [ -z $custid_at_host ]
+
+    if [ -z "$feeduser" ] || [ -z "$custid_at_host" ]
     then
       log_err "Could not determine credentials, aborting synchronization."
-      rm -rf $FEED_INFO_TEMP_DIR
+      rm -rf "$FEED_INFO_TEMP_DIR"
       exit 1
     fi
 
@@ -289,32 +304,32 @@ is_feed_current () {
       fi
     fi
     create_tmp_key
-    rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $TMPACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:/scap-data/timestamp $FEED_INFO_TEMP_DIR
+    rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $TMPACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:$GSF_RSYNC_PATH/timestamp "$FEED_INFO_TEMP_DIR"
     if [ $? -ne 0 ]
     then
       log_err "rsync failed, aborting synchronization."
-      rm -rf $FEED_INFO_TEMP_DIR
+      rm -rf "$FEED_INFO_TEMP_DIR"
       remove_tmp_key
       exit 1
     fi
     remove_tmp_key
   else
     log_notice "No Greenbone Security Feed access key found, falling back to Greenbone Community Feed"
-    eval "$RSYNC -ltvrP \"$COMMUNITY_SCAP_RSYNC_FEED/timestamp\" \"$FEED_INFO_TEMP_DIR\""
+    eval "$RSYNC -ltvrP \"$COMMUNITY_RSYNC_FEED/timestamp\" \"$FEED_INFO_TEMP_DIR\""
     if [ $? -ne 0 ]
     then
       log_err "rsync failed, aborting synchronization."
-      rm -rf $FEED_INFO_TEMP_DIR
+      rm -rf "$FEED_INFO_TEMP_DIR"
       exit 1
     fi
   fi
 
-  FEED_VERSION_SERVER=`cat $FEED_INFO_TEMP_DIR/timestamp`
+  FEED_VERSION_SERVER=`cat "$FEED_INFO_TEMP_DIR/timestamp"`
 
   if [ -z "$FEED_VERSION_SERVER" ]
   then
     log_err "Could not determine server feed version."
-    rm -rf $FEED_INFO_TEMP_DIR
+    rm -rf "$FEED_INFO_TEMP_DIR"
     exit 1
   fi
 
@@ -326,13 +341,13 @@ is_feed_current () {
   fi
 
   # Cleanup
-  rm -rf $FEED_INFO_TEMP_DIR
+  rm -rf "$FEED_INFO_TEMP_DIR"
 
   return $FEED_CURRENT
 }
 
 do_help () {
-  echo "$0: Sync SCAP data"
+  echo "$0: Sync feed data"
 
   if [ -e $ACCESSKEY ]
   then
@@ -345,31 +360,22 @@ do_help () {
   echo " --feedversion     display version of this feed"
   echo " --help            display this help"
   echo " --identify        display information"
-  echo " --refresh         update database without downloading new state"
-  echo " --refresh-private update database using only user data"
   echo " --selftest        perform self-test"
   echo " --version         display version"
-  echo " --verbose         enable verbose log messages"
   echo ""
   exit 0
 }
 
 do_rsync_community_feed () {
-  if [ -z "$COMMUNITY_SCAP_RSYNC_FEED" ]; then
-    COMMUNITY_SCAP_RSYNC_FEED=rsync://feed.community.greenbone.net:/scap-data
-    # An alternative syntax which might work if the above doesn't:
-    # COMMUNITY_SCAP_RSYNC_FEED=rsync@feed.community.greenbone.net::scap-data
-  fi
-
   if [ -z "$RSYNC" ]; then
     log_err "rsync not found!"
   else
     log_notice "Using rsync: $RSYNC"
-    log_notice "Configured SCAP data rsync feed: $COMMUNITY_SCAP_RSYNC_FEED"
-    mkdir -p "$SCAP_DIR"
-    eval "$RSYNC -ltvrP $RSYNC_DELETE \"$COMMUNITY_SCAP_RSYNC_FEED\" \"$SCAP_DIR\""
+    log_notice "Configured $FEED_TYPE_LONG rsync feed: $COMMUNITY_RSYNC_FEED"
+    mkdir -p "$FEED_DIR"
+    eval "$RSYNC -ltvrP $RSYNC_DELETE \"$COMMUNITY_RSYNC_FEED\" \"$FEED_DIR\""
     if [ $? -ne 0 ] ; then
-      log_err "rsync failed. Your SCAP data might be broken now."
+      log_err "rsync failed. Your $FEED_TYPE_LONG might be broken now."
       exit 1
     fi
   fi
@@ -386,16 +392,16 @@ do_sync_community_feed () {
   fi
 }
 
-sync_scapdata(){
+sync_feed_data(){
   if [ -e $ACCESSKEY ]
   then
-    log_notice "Found Greenbone Security Feed subscription file, trying to synchronize with Greenbone SCAP data Repository ..."
+    log_notice "Found Greenbone Security Feed subscription file, trying to synchronize with Greenbone $FEED_TYPE_LONG Repository ..."
     notsynced=1
-    retried=0
 
-    mkdir -p "$SCAP_DIR"
+    mkdir -p "$FEED_DIR"
     read feeduser < $ACCESSKEY
     custid_at_host=`head -1 $ACCESSKEY | cut -d : -f 1`
+
     if [ -z "$feeduser" ] || [ -z "$custid_at_host" ]
     then
       log_err "Could not determine credentials, aborting synchronization."
@@ -423,8 +429,8 @@ sync_scapdata(){
         fi
       fi
       create_tmp_key
-      rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $ACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:/scap-data/ $SCAP_DIR
-      if [ 0 != "$?" ] ; then
+      rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $ACCESSKEY" -ltvrP --chmod=D+x $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:$GSF_RSYNC_PATH/ $FEED_DIR
+      if [ 0 -ne "$?" ] ; then
         log_err "rsync failed, aborting synchronization."
         remove_tmp_key
         exit 1
@@ -432,7 +438,7 @@ sync_scapdata(){
       remove_tmp_key
       notsynced=0
     done
-    log_notice "Synchronization with the Greenbone SCAP data Repository successful."
+    log_notice "Synchronization with the Greenbone $FEED_TYPE_LONG Repository successful."
   else
     log_notice "No Greenbone Security Feed access key found, falling back to Greenbone Community Feed"
     do_sync_community_feed
@@ -462,46 +468,55 @@ do_self_test () {
 ########## START
 ########## =====
 
+while test $# -gt 0; do
+  case "$1" in
+    "--version"|"--identify"|"--describe"|"--feedversion"|"--help"|"--selftest"|"--feedcurrent")
+      if [ -z "$ACTION" ] ; then
+        ACTION="$1"
+      fi
+      ;;
+  esac
+  shift
+done
+
+FEED_TYPE="SCAP"
+
+init_feed_type
+
 write_feed_xml
 
-while test $# -gt 0; do
- case "$1" in
-        --version)
-          echo $VERSION
-          exit 0
-           ;;
-        --identify)
-          echo "SCAPSYNC|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|SCAPSYNC"
-          exit 0
-          ;;
-        --describe)
-          do_describe
-          exit 0
-          ;;
-        --feedversion)
-          do_feedversion
-          exit 0
-          ;;
-        --help)
-          do_help
-          exit 0
-          ;;
-        --verbose)
-          VERBOSE=1
-          ;;
-        --selftest)
-          SELFTEST_FAIL=0
-          SELFTEST_STDERR=1
-          do_self_test
-          exit $SELFTEST_FAIL
-          ;;
-        --feedcurrent)
-          is_feed_current
-          exit $?
-          ;;
-      esac
-      shift
-done
+case "$ACTION" in
+  --version)
+    echo $VERSION
+    exit 0
+    ;;
+  --identify)
+    echo "$SCRIPT_ID|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|$SCRIPT_ID"
+    exit 0
+    ;;
+  --describe)
+    do_describe
+    exit 0
+    ;;
+  --feedversion)
+    do_feedversion
+    exit 0
+    ;;
+  --help)
+    do_help
+    exit 0
+    ;;
+  --selftest)
+    SELFTEST_FAIL=0
+    SELFTEST_STDERR=1
+    do_self_test
+    exit $SELFTEST_FAIL
+    ;;
+  --feedcurrent)
+    is_feed_current
+    exit $?
+    ;;
+esac
 
 SELFTEST_FAIL=0
 do_self_test
@@ -509,7 +524,6 @@ if [ $SELFTEST_FAIL -ne 0 ]
 then
   exit 1
 fi
-
 
 is_feed_current
 if [ $FEED_CURRENT -eq 1 ]
@@ -524,7 +538,7 @@ fi
     log_notice "Sync in progress, exiting."
     exit 1
   fi
-  sync_scapdata
+  sync_feed_data
   echo -n > $LOCK_FILE
 ) 9>$LOCK_FILE
 
