* tools/greenbone-certdata-sync.in, tools/greenbone-scapdata-sync.in, tools/openvas-certdata-sync.in, tools/openvas-scapdata-sync.in: Replace any tabs by spaces.
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-manager@23184 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/greenbone-certdata-sync.in b/tools/greenbone-certdata-sync.in
--- a/tools/greenbone-certdata-sync.in
+++ b/tools/greenbone-certdata-sync.in
@@ -448,14 +448,14 @@ do_help () {
   then
     echo " --database       database name"
   fi
-  echo " --describe	display current feed info"
-  echo " --feedversion	display version of this feed"
-  echo " --help		display this help"
-  echo " --identify	display information"
-  echo " --migrate	update database without downloading new state"
-  echo " --refresh	update database without downloading new state"
-  echo " --selftest	perform self-test"
-  echo " --version	display version"
+  echo " --describe     display current feed info"
+  echo " --feedversion  display version of this feed"
+  echo " --help         display this help"
+  echo " --identify     display information"
+  echo " --migrate      update database without downloading new state"
+  echo " --refresh      update database without downloading new state"
+  echo " --selftest     perform self-test"
+  echo " --version      display version"
   echo ""
   exit 0
 }
@@ -512,20 +512,20 @@ update_cvss () {
       until [ "$try_sql" -eq 0 ]
       do
         sql "${ATTACH_SCAP}
-			 ${RECURSIVE_TRIGGERS_OFF}
-			 UPDATE ${SCHEMA_CERT}cert_bund_advs
-			   SET max_cvss =
-				   (
-					 SELECT max(cvss)
-					 FROM scap.cves
-					 WHERE name IN
-					   (
-						 SELECT cve_name
-						 FROM ${SCHEMA_CERT}cert_bund_cves
-						 WHERE adv_id=cert_bund_advs.id
-					   )
-					   AND cvss != 0.0
-				   );"
+             ${RECURSIVE_TRIGGERS_OFF}
+             UPDATE ${SCHEMA_CERT}cert_bund_advs
+               SET max_cvss =
+                   (
+                     SELECT max(cvss)
+                     FROM scap.cves
+                     WHERE name IN
+                       (
+                         SELECT cve_name
+                         FROM ${SCHEMA_CERT}cert_bund_cves
+                         WHERE adv_id=cert_bund_advs.id
+                       )
+                       AND cvss != 0.0
+                   );"
         test_sql_exit "Could not update CVSS scores for CERT-Bund Advisories"
       done
     else
@@ -540,20 +540,20 @@ update_cvss () {
       until [ "$try_sql" -eq 0 ]
       do
         sql "${ATTACH_SCAP}
-			 ${RECURSIVE_TRIGGERS_OFF}
-			 UPDATE ${SCHEMA_CERT}dfn_cert_advs
-			   SET max_cvss =
-				   (
-					 SELECT max(cvss)
-					 FROM scap.cves
-					 WHERE name IN
-					   (
-						 SELECT cve_name
-						 FROM ${SCHEMA_CERT}dfn_cert_cves
-						 WHERE adv_id=dfn_cert_advs.id
-					   )
-					   AND cvss != 0.0
-				   );"
+             ${RECURSIVE_TRIGGERS_OFF}
+             UPDATE ${SCHEMA_CERT}dfn_cert_advs
+               SET max_cvss =
+                   (
+                     SELECT max(cvss)
+                     FROM scap.cves
+                     WHERE name IN
+                       (
+                         SELECT cve_name
+                         FROM ${SCHEMA_CERT}dfn_cert_cves
+                         WHERE adv_id=dfn_cert_advs.id
+                       )
+                       AND cvss != 0.0
+                   );"
         test_sql_exit "Could not update CVSS scores for DFN-CERT Advisories"
       done
     else
@@ -779,25 +779,25 @@ do_self_test () {
 
   if [ $POSTGRES -eq 1 ] ;
   then
-	POSTGRESQL=`command -v psql`
-	if [ -z "$POSTGRESQL" ]; then
-	  if [ 0 -ne $SELFTEST_STDERR ]
-	  then
-		echo "psql not found (required)." 1>&2
-	  fi
-	  log_err "psql not found (required)."
-	  SELFTEST_FAIL=1
-	fi
+    POSTGRESQL=`command -v psql`
+    if [ -z "$POSTGRESQL" ]; then
+      if [ 0 -ne $SELFTEST_STDERR ]
+      then
+        echo "psql not found (required)." 1>&2
+      fi
+      log_err "psql not found (required)."
+      SELFTEST_FAIL=1
+    fi
   else
-	SQLITE=`command -v sqlite3`
-	if [ -z "$SQLITE" ]; then
-	  if [ 0 -ne $SELFTEST_STDERR ]
-	  then
-		echo "sqlite3 not found (required)." 1>&2
-	  fi
-	  log_err "sqlite3 not found (required)."
-	  SELFTEST_FAIL=1
-	fi
+    SQLITE=`command -v sqlite3`
+    if [ -z "$SQLITE" ]; then
+      if [ 0 -ne $SELFTEST_STDERR ]
+      then
+        echo "sqlite3 not found (required)." 1>&2
+      fi
+      log_err "sqlite3 not found (required)."
+      SELFTEST_FAIL=1
+    fi
   fi
 
   if [ -z "$RSYNC" ]
@@ -824,21 +824,21 @@ do_self_test () {
 psql_setup "tasks"
 while test $# -gt 0; do
  case "$1" in
-		--database)
-		  if [ $POSTGRES -eq 1 ] ;
-		  then
-			shift
-			if [ $# -gt 0 ]; then
-			  psql_setup $1
-			else
-			  echo "[e] --database argument missing"
-			  exit 1
-			fi
-		  else
-			echo "[e] --database option available only for Postgres"
-			exit 1
-		  fi
-		  ;;
+        --database)
+          if [ $POSTGRES -eq 1 ] ;
+          then
+            shift
+            if [ $# -gt 0 ]; then
+              psql_setup $1
+            else
+              echo "[e] --database argument missing"
+              exit 1
+            fi
+          else
+            echo "[e] --database option available only for Postgres"
+            exit 1
+          fi
+          ;;
         --version)
           echo $VERSION
           exit 0
diff --git a/tools/greenbone-scapdata-sync.in b/tools/greenbone-scapdata-sync.in
--- a/tools/greenbone-scapdata-sync.in
+++ b/tools/greenbone-scapdata-sync.in
@@ -638,10 +638,10 @@ check_db_version () {
          reinit
        else
          db_migrate_9
-		 db_migrate_10
-		 db_migrate_11
-		 db_migrate_12
-		 db_migrate_13
+         db_migrate_10
+         db_migrate_11
+         db_migrate_12
+         db_migrate_13
          db_migrate_14
          db_migrate_15
        fi;;
@@ -655,17 +655,17 @@ check_db_version () {
          db_migrate_13
          db_migrate_14
          db_migrate_15
-	   fi;;
+       fi;;
    10) if [ $POSTGRES -eq 1 ]
        then
          reinit
        else
          db_migrate_11
-		 db_migrate_12
-		 db_migrate_13
-		 db_migrate_14
+         db_migrate_12
+         db_migrate_13
+         db_migrate_14
          db_migrate_15
-	    fi;;
+        fi;;
    11) if [ $POSTGRES -eq 1 ]
        then
          reinit
@@ -674,7 +674,7 @@ check_db_version () {
          db_migrate_13
          db_migrate_14
          db_migrate_15
-	   fi;;
+       fi;;
    12) if [ $POSTGRES -eq 1 ]
        then
          reinit
@@ -1355,25 +1355,25 @@ do_self_test () {
 
   if [ $POSTGRES -eq 1 ] ;
   then
-	POSTGRESQL=`command -v psql`
-	if [ -z "$POSTGRESQL" ]; then
-	  if [ 0 -ne $SELFTEST_STDERR ]
-	  then
-		echo "psql not found (required)." 1>&2
-	  fi
-	  log_err "psql not found (required)."
-	  SELFTEST_FAIL=1
-	fi
+    POSTGRESQL=`command -v psql`
+    if [ -z "$POSTGRESQL" ]; then
+      if [ 0 -ne $SELFTEST_STDERR ]
+      then
+        echo "psql not found (required)." 1>&2
+      fi
+      log_err "psql not found (required)."
+      SELFTEST_FAIL=1
+    fi
   else
-	SQLITE=`command -v sqlite3`
-	if [ -z "$SQLITE" ]; then
-	  if [ 0 -ne $SELFTEST_STDERR ]
-	  then
-		echo "sqlite3 not found (required)." 1>&2
-	  fi
-	  log_err "sqlite3 not found (required)."
-	  SELFTEST_FAIL=1
-	fi
+    SQLITE=`command -v sqlite3`
+    if [ -z "$SQLITE" ]; then
+      if [ 0 -ne $SELFTEST_STDERR ]
+      then
+        echo "sqlite3 not found (required)." 1>&2
+      fi
+      log_err "sqlite3 not found (required)."
+      SELFTEST_FAIL=1
+    fi
   fi
 
   if [ -z "$RSYNC" ]
@@ -1420,21 +1420,21 @@ while test $# -gt 0; do
           do_help
           exit 0
           ;;
-		--database)
-		  if [ $POSTGRES -eq 1 ] ;
-		  then
-			shift
-			if [ $# -gt 0 ]; then
-			  psql_setup $1
-			else
-			  echo "[e] --database argument missing"
-			  exit 1
-			fi
-		  else
-			echo "[e] --database option available only for Postgres"
-			exit 1
-		  fi
-		  ;;
+        --database)
+          if [ $POSTGRES -eq 1 ] ;
+          then
+            shift
+            if [ $# -gt 0 ]; then
+              psql_setup $1
+            else
+              echo "[e] --database argument missing"
+              exit 1
+            fi
+          else
+            echo "[e] --database option available only for Postgres"
+            exit 1
+          fi
+          ;;
         --verbose)
           VERBOSE=1
           ;;
diff --git a/tools/openvas-certdata-sync.in b/tools/openvas-certdata-sync.in
--- a/tools/openvas-certdata-sync.in
+++ b/tools/openvas-certdata-sync.in
@@ -696,19 +696,19 @@ if [ -n "$1" ]; then
         exit 0
         ;;
       --database)
-		if [ $POSTGRES -eq 1 ] ;
-		then
-		  shift
+        if [ $POSTGRES -eq 1 ] ;
+        then
+          shift
           if [ $# -gt 0 ]; then
-		    psql_setup $1
-	      else
-			echo "[e] --database argument missing"
-			exit 1
-		  fi
-		else
-		  echo "[e] --database option available only for Postgres"
-		  exit 1
-		fi
+            psql_setup $1
+          else
+            echo "[e] --database argument missing"
+            exit 1
+          fi
+        else
+          echo "[e] --database option available only for Postgres"
+          exit 1
+        fi
         ;;
     esac
     shift
diff --git a/tools/openvas-scapdata-sync.in b/tools/openvas-scapdata-sync.in
--- a/tools/openvas-scapdata-sync.in
+++ b/tools/openvas-scapdata-sync.in
@@ -113,17 +113,17 @@ SPLIT_PART_SIZE=0
 
 do_help () {
   echo "$0: Sync SCAP data using different protocols"
-  echo " --rsync		sync with rsync (default)"
-  echo " --migrate		migrate database without downloading feed data"
-  echo " --refresh		update database without downloading feed data"
-  echo " --refresh-private	update database only using private data"
-  echo " --check		just checksum check"
+  echo " --rsync                sync with rsync (default)"
+  echo " --migrate              migrate database without downloading feed data"
+  echo " --refresh              update database without downloading feed data"
+  echo " --refresh-private      update database only using private data"
+  echo " --check                just checksum check"
   echo "OpenVAS administrator functions:"
-  echo " --selftest	perform self-test"
-  echo " --identify	display information"
-  echo " --version	display version"
-  echo " --describe	display current scap feed info"
-  echo " --feedversion   display current scap feed version"
+  echo " --selftest     perform self-test"
+  echo " --identify     display information"
+  echo " --version      display version"
+  echo " --describe     display current scap feed info"
+  echo " --feedversion  display current scap feed version"
   echo "Options:"
   echo " --verbose       enable verbose log messages"
   if [ $POSTGRES -eq 1 ];
@@ -132,10 +132,10 @@ do_help () {
   fi
   echo ""
   echo "Environment variables:"
-  echo "SCAP_DIR		where to extract plugins (absolute path)"
-  echo "OV_RSYNC_FEED	URL of rsync feed"
-  echo "OV_HTTP_FEED	URL of http feed"
-  echo "TMPDIR		temporary directory used to download the files"
+  echo "SCAP_DIR        where to extract plugins (absolute path)"
+  echo "OV_RSYNC_FEED   URL of rsync feed"
+  echo "OV_HTTP_FEED    URL of http feed"
+  echo "TMPDIR          temporary directory used to download the files"
   echo "PRIVATE_SUBDIR  subdirectory to exclude from deletion by rsync"
   echo "Note that you can use standard ones as well (e.g. http_proxy) for wget/curl"
   echo ""
@@ -1248,19 +1248,19 @@ if [ -n "$1" ]; then
         exit 0
         ;;
       --database)
-		if [ $POSTGRES -eq 1 ] ;
-		then
-		  shift
+        if [ $POSTGRES -eq 1 ] ;
+        then
+          shift
           if [ $# -gt 0 ]; then
-		    psql_setup $1
-	      else
-			echo "[e] --database argument missing"
-			exit 1
-		  fi
-		else
-		  echo "[e] --database option available only for Postgres"
-		  exit 1
-		fi
+            psql_setup $1
+          else
+            echo "[e] --database argument missing"
+            exit 1
+          fi
+        else
+          echo "[e] --database option available only for Postgres"
+          exit 1
+        fi
         ;;
       --verbose)
         VERBOSE=1
