Extract syncing the enterprise into an own function
Extract a do_sync_enterprise_feed function from sync_feed_data as we
already have a do_sync_community_feed function.

diff --git a/tools/greenbone-feed-sync.in b/tools/greenbone-feed-sync.in
--- a/tools/greenbone-feed-sync.in
+++ b/tools/greenbone-feed-sync.in
@@ -465,44 +465,49 @@ do_sync_community_feed () {
   fi
 }
 
+do_sync_enterprise_feed () {
+  log_notice "Found Greenbone Enterprise Feed access key, trying to synchronize with Greenbone $FEED_TYPE_LONG Repository ..."
+  notsynced=1
+
+  mkdir -p "$FEED_DIR"
+  read feeduser < $ACCESSKEY
+  if [ -z "$ENTERPRISE_FEED_HOST_OVERRIDE" ]
+  then
+    custid_at_host=`head -1 $ACCESSKEY | cut -d : -f 1`
+  else
+    custid=`head -1 $ACCESSKEY | cut -d @ -f 1`
+    custid_at_host="${custid}@${ENTERPRISE_FEED_HOST_OVERRIDE}"
+  fi
+
+  if [ -z "$feeduser" ] || [ -z "$custid_at_host" ]
+  then
+    log_err "Could not determine credentials, aborting synchronization."
+    exit 1
+  fi
+
+  while [ 0 -ne "$notsynced" ]
+  do
+
+    RSYNC_SSH_PROXY_CMD=""
+
+    create_tmp_key
+    rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $ACCESSKEY" -ltvrP $RSYNC_CHMOD $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:$GSF_RSYNC_PATH/ $FEED_DIR
+    if [ 0 -ne "$?" ]; then
+      log_err "rsync failed, aborting synchronization."
+      remove_tmp_key
+      exit 1
+    fi
+    remove_tmp_key
+    notsynced=0
+  done
+
+  log_notice "Synchronization with the Greenbone $FEED_TYPE_LONG Repository successful."
+}
+
 sync_feed_data(){
   if [ -e $ACCESSKEY ]
   then
-    log_notice "Found Greenbone Enterprise Feed access key, trying to synchronize with Greenbone $FEED_TYPE_LONG Repository ..."
-    notsynced=1
-
-    mkdir -p "$FEED_DIR"
-    read feeduser < $ACCESSKEY
-    if [ -z "$ENTERPRISE_FEED_HOST_OVERRIDE" ]
-    then
-      custid_at_host=`head -1 $ACCESSKEY | cut -d : -f 1`
-    else
-      custid=`head -1 $ACCESSKEY | cut -d @ -f 1`
-      custid_at_host="${custid}@${ENTERPRISE_FEED_HOST_OVERRIDE}"
-    fi
-
-    if [ -z "$feeduser" ] || [ -z "$custid_at_host" ]
-    then
-      log_err "Could not determine credentials, aborting synchronization."
-      exit 1
-    fi
-
-    while [ 0 -ne "$notsynced" ]
-    do
-
-      RSYNC_SSH_PROXY_CMD=""
-
-      create_tmp_key
-      rsync -e "ssh $RSYNC_SSH_OPTS $RSYNC_SSH_PROXY_CMD -p $PORT -i $ACCESSKEY" -ltvrP $RSYNC_CHMOD $RSYNC_DELETE $RSYNC_COMPRESS $custid_at_host:$GSF_RSYNC_PATH/ $FEED_DIR
-      if [ 0 -ne "$?" ]; then
-        log_err "rsync failed, aborting synchronization."
-        remove_tmp_key
-        exit 1
-      fi
-      remove_tmp_key
-      notsynced=0
-    done
-    log_notice "Synchronization with the Greenbone $FEED_TYPE_LONG Repository successful."
+    do_sync_enterprise_feed
   else
     do_sync_community_feed
   fi
