* tools/greenbone-scapdata-sync: Add command line option --selftest and moved command lin eparsing to bottom.
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-manager@14448 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/greenbone-scapdata-sync b/tools/greenbone-scapdata-sync
--- a/tools/greenbone-scapdata-sync
+++ b/tools/greenbone-scapdata-sync
@@ -92,28 +92,6 @@ do_feedversion () {
   fi
 }
 
-while test $# -gt 0; do
- case "$1" in
-        --version)
-          echo $VERSION
-          exit 0
-           ;;
-        --identify)
-          echo "SCAPSYNC|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|SCAPSYNC"
-          exit 0
-          ;;
-        --describe)
-          do_describe
-          exit 0
-          ;;
-        --feedversion)
-          do_feedversion
-          exit 0
-          ;;
- esac
- shift
-done
-
 if [[ ! -w $LOGDIR ]]
 then
   NOLOG=1
@@ -361,4 +339,40 @@ sync_scapdata(){
   fi
 }
 
+do_self_test () {
+  if [ -z "$SQLITE" ]; then
+    echo "[e] Error: sqlite3 not found (required)";
+    SELFTEST_FAIL=1
+  fi
+}
+
+while test $# -gt 0; do
+ case "$1" in
+        --version)
+          echo $VERSION
+          exit 0
+           ;;
+        --identify)
+          echo "SCAPSYNC|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|SCAPSYNC"
+          exit 0
+          ;;
+        --describe)
+          do_describe
+          exit 0
+          ;;
+        --feedversion)
+          do_feedversion
+          exit 0
+          ;;
+        --selftest)
+          SELFTEST_FAIL=0
+          do_self_test
+          exit $SELFTEST_FAIL
+          ;;
+ esac
+ shift
+done
+
 sync_scapdata
+
+exit 0
