Merging openvas-cert-sync into greenbone-cert-sync in order to maintain only a single sync script instead of two mostly identical ones.
* CMakeLists.txt: Drop handling of openvas-certdata-sync.in.

* src/omp.c (cert_script): Rename from openvas-cert-sync to
greenbone-nvt-sync.

* tools/greenbone-certdata-sync.in: Merged some parts from
openvas-cert-sync here to make the script flexibel to
sync either from GSF or from community feed.

* tools/openvas-certdata-sync.in: Removed.



git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-manager@24621 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/greenbone-certdata-sync.in b/tools/greenbone-certdata-sync.in
--- a/tools/greenbone-certdata-sync.in
+++ b/tools/greenbone-certdata-sync.in
@@ -1,14 +1,16 @@
 #!/bin/sh
 #
 # greenbone-certdata-sync
-# This script synchronizes an OpenVAS installation with the Greenbone CERT
-# data directory.
+# This script synchronizes an OpenVAS installation with the
+# CERT data from either the Greenbone Security Feed (in
+# case a GSF access key is present) or else from the Greenbone
+# Community Feed.
 #
 # Authors:
 # Timo Pollmeier <timo.pollmeier@greenbone.net>
 #
 # Copyright:
-# Copyright (C) 2011-2014 Greenbone Networks GmbH
+# Copyright (C) 2011-2016 Greenbone Networks GmbH
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -24,8 +26,7 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 
-VERSION=20140808
-RESTRICTED=1
+VERSION=@OPENVASMD_VERSION@
 
 # SETTINGS
 # ========
@@ -55,7 +56,7 @@ fi
 # "--delete --exclude cert.db --exclude $PRIVATE_SUBDIR/",
 # which means that files which are not part of the feed, database or private
 # directory will be deleted.
-RSYNC_DELETE="--delete --exclude cert.db --exclude $PRIVATE_SUBDIR/"
+RSYNC_DELETE="--delete --exclude cert.db --exclude \"$PRIVATE_SUBDIR/\""
 
 # RSYNC_SSH_OPTS contains options which should be passed to ssh for the rsync
 # connection to the repository.
@@ -85,6 +86,7 @@ ENABLED=1
 # Manager database. This can be controlled via the --refresh parameter.
 REFRESH_ONLY=0
 
+# The call with default parameters of sqlite3.
 SQLITE3="sqlite3 -noheader -bail"
 
 # PSQL defines the name of the Postgres binary to call, along with additional
@@ -104,7 +106,7 @@ if [ -z "$SQL_RETRY_DELAY" ]; then
   SQL_RETRY_DELAY="10m" # allowed unit suffixes: see sleep command
 fi
 
-[ -r @OPENVAS_SYSCONF_DIR@/greenbone-certdata-sync.conf ] && . @OPENVAS_SYSCONF_DIR@/greenbone-certdata-sync.conf
+[ -r \"@OPENVAS_SYSCONF_DIR@/greenbone-certdata-sync.conf\" ] && . \"@OPENVAS_SYSCONF_DIR@/greenbone-certdata-sync.conf\"
 
 BASE_SYNC_DIR="@OPENVAS_STATE_DIR@"
 CERT_DIR="@OPENVAS_CERT_DATA_DIR@"
@@ -119,21 +121,52 @@ if [ ! $POSTGRES -eq 1 ] ; then
   ATTACH_SCAP="ATTACH DATABASE '$SCAP_DB' AS scap;"
 fi
 
-ACCESSKEY="@OPENVAS_SYSCONF_DIR@/gsf-access-key"
-
 TIMESTAMP="$CERT_DIR/timestamp"
 
-if [ -z "$FEED_NAME" ] ; then
-  FEED_NAME="Greenbone CERT Feed"
+ACCESSKEY="@OPENVAS_SYSCONF_DIR@/gsf-access-key"
+
+# Determine whether a GSF access key is present. If yes,
+# then use the Greenbone Security Feed. Else use the
+# Greenbone Community Feed.
+if [ -e $ACCESSKEY ]
+then
+  RESTRICTED=1
+
+  if [ -z "$FEED_NAME" ] ; then
+    FEED_NAME="Greenbone CERT Feed"
+  fi
+
+  if [ -z "$FEED_VENDOR" ] ; then
+    FEED_VENDOR="Greenbone Networks GmbH"
+  fi
+
+  if [ -z "$FEED_HOME" ] ; then
+    FEED_HOME="http://www.greenbone.net/technology/gsf.html"
+  fi
+
+else
+  RESTRICTED=0
+
+  if [ -z "$FEED_NAME" ] ; then
+    FEED_NAME="OpenVAS CERT Feed"
+  fi
+
+  if [ -z "$FEED_VENDOR" ] ; then
+    FEED_VENDOR="The OpenVAS Project"
+  fi
+
+  if [ -z "$FEED_HOME" ] ; then
+    FEED_HOME="http://www.openvas.org/"
+  fi
+
+  if [ -z "$COMMUNITY_CERT_RSYNC_FEED" ]; then
+    COMMUNITY_CERT_RSYNC_FEED=rsync://feed.openvas.org:/cert-data
+    # An alternative syntax which might work if the above doesn't:
+    # COMMUNITY_CERT_RSYNC_FEED=rsync@feed.openvas.org::cert-data
+  fi
+
 fi
 
-if [ -z "$FEED_VENDOR" ] ; then
-  FEED_VENDOR="Greenbone Networks GmbH"
-fi
-
-if [ -z "$FEED_HOME" ] ; then
-  FEED_HOME="http://www.greenbone.net/technology/gsf.html"
-fi
 
 RSYNC=`command -v rsync`
 
@@ -178,11 +211,11 @@ handle_interrupt () {
 }
 
 # This function uses gos-state-manager to get information about the settings.
-# If not gos-state-manager is installed this values of the settings can not be
-# retrieved.
+# gos-state-manager is only available on a Greenbone OS.
+# If gos-state-manager is missing the settings values can not be retrieved.
 #
 # Input: option
-# Output: value as string or empty String if gos-state-manager is not installed
+# Output: value as string or empty String if gos-state-manager is missing
 #         or option not set
 get_value ()
 {
@@ -328,9 +361,14 @@ is_feed_current () {
         exit -1
       fi
     else
-      log_err "Could not find access key, aborting synchronization."
-      rm -rf $FEED_INFO_TEMP_DIR
-      exit -1
+      log_notice "No Greenbone Security Feed accees key found, falling back to Greenbone Community Feed"
+      eval "$RSYNC -ltvrP \"$COMMUNITY_CERT_RSYNC_FEED/timestamp\" \"$FEED_INFO_TEMP_DIR\""
+      if [ $? -ne 0 ]
+      then
+        log_err "rsync failed, aborting synchronization."
+        rm -rf $FEED_INFO_TEMP_DIR
+        exit -1
+      fi
     fi
 
     FEED_VERSION_SERVER=`cat $FEED_INFO_TEMP_DIR/timestamp`
@@ -390,7 +428,7 @@ sql_pg () {
   exit_code=$?
   if [ 0 -ne "$exit_code" ]
   then
-    echo "[e] psql exited with code $exit_code for sql: $1."
+    log_err "psql exited with code $exit_code for sql: $1."
     exit 1
   fi
 }
@@ -467,15 +505,24 @@ check_db_version () {
 
 do_help () {
   echo "$0: Sync CERT data"
+
+  if [ -e $ACCESSKEY ]
+  then
+    echo "GSF access key found: Using Greenbone Security Feed"
+  else
+    echo "No GSF access key found: Using Community Feed"
+  fi
+
   if [ $POSTGRES -eq 1 ];
   then
-    echo " --database       database name"
+    echo " --database     database name"
   fi
+
   echo " --describe     display current feed info"
   echo " --feedversion  display version of this feed"
   echo " --help         display this help"
   echo " --identify     display information"
-  echo " --migrate      update database without downloading new state"
+  echo " --migrate      migrate database without downloading new state"
   echo " --refresh      update database without downloading new state"
   echo " --selftest     perform self-test"
   echo " --version      display version"
@@ -740,6 +787,32 @@ update_cert_db() {
   done
 }
 
+do_rsync_community_feed () {
+  if [ -z "$RSYNC" ]; then
+    log_err "rsync not found!"
+  else
+    log_notice "Using rsync: $RSYNC"
+    log_notice "Configured CERT data rsync feed: $COMMUNITY_CERT_RSYNC_FEED"
+    mkdir -p "$CERT_DIR"
+    eval "$RSYNC -ltvrP $RSYNC_DELETE \"$COMMUNITY_CERT_RSYNC_FEED\" \"$CERT_DIR\""
+    if [ $? -ne 0 ] ; then
+      log_err "rsync failed. Your CERT data might be broken now."
+      exit 1
+    fi
+  fi
+}
+
+do_sync_community_feed () {
+  if [ -z "$RSYNC" ] ; then
+    log_err "rsync not found!"
+    log_err "No utility available in PATH environment variable to download Feed data"
+    exit 1
+  else
+    log_notice "Will use rsync"
+    do_rsync_community_feed
+  fi
+}
+
 sync_certdata(){
   if [ $REFRESH_ONLY -eq 0 ]
   then
@@ -789,8 +862,8 @@ sync_certdata(){
       echo
 
     else
-      log_err "gsf-access-key not found, aborting synchronization."
-      exit 1
+      log_notice "No Greenbone Security Feed accees key found, falling back to Greenbone Community Feed"
+      do_sync_community_feed
     fi
   fi
 
