Update gvm-lsc-deb-creator

diff --git a/tools/gvm-lsc-deb-creator b/tools/gvm-lsc-deb-creator
--- a/tools/gvm-lsc-deb-creator
+++ b/tools/gvm-lsc-deb-creator
@@ -1,4 +1,28 @@
 #!/bin/bash
+# Copyright (C) 2018-2022 Greenbone AG
+#
+# SPDX-License-Identifier: AGPL-3.0-or-later
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU Affero General Public License as
+# published by the Free Software Foundation, either version 3 of the
+# License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Affero General Public License for more details.
+#
+# You should have received a copy of the GNU Affero General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+# This script generates a Debian package that creates a user for GVM
+# local security checks.
+
+#
+# Variables
+#
+
 # Command line parameters
 USERNAME="$1"
 PUBKEY_FILE="$2"
@@ -88,6 +112,14 @@ then
   exit 1
 fi
 
+#
+# Set up error handling
+#
+handle_error() {
+  echo "DEB package generation failed" >&2
+  exit 1
+}
+trap handle_error ERR
 
 #
 # Create data files
