Satisfied all remaining shellcheck warnings:
* Replaced all remaining $.. with "$..".

* Replaced raw $? checks with better  ||, && and "if" checks.

* Packed chains of 'echo ".." >> $x; echo ".." >> $x' with better
  '{ echo ".."; echo ".." } >> $x'.

* exported locally unused variables (that are probably needed by other
  scripts).

diff --git a/tools/gvm-manage-certs.in b/tools/gvm-manage-certs.in
--- a/tools/gvm-manage-certs.in
+++ b/tools/gvm-manage-certs.in
@@ -37,7 +37,7 @@ SERVER_CERTIFICATE=2
 CLIENT_CERTIFICATE=3
 
 log_write () {
-  if [ $QUIET -ne 1 ]
+  if [ "$QUIET" -ne 1 ]
   then
     $LOG_CMD -p daemon.info "$1"
     echo "$1"
@@ -50,7 +50,7 @@ log_err () {
 }
 
 log_debug () {
-  if [ $DEBUG -eq 1 ]
+  if [ "$DEBUG" -eq 1 ]
   then
     $LOG_CMD -p daemon.debug "$1"
     echo "$1"
@@ -58,7 +58,7 @@ log_debug () {
 }
 
 log_verbose () {
-  if [ $VERBOSE -eq 1 ]
+  if [ "$VERBOSE" -eq 1 ]
   then
     log_write "$1"
   fi
@@ -84,11 +84,7 @@ set_defaults () {
   # Hostname
   if [ -z "$GVM_CERTIFICATE_HOSTNAME" ]
   then
-    GVM_CERTIFICATE_HOSTNAME=$(hostname --fqdn 2> /dev/null)
-    if [ $? -ne 0 ]
-    then
-      GVM_CERTIFICATE_HOSTNAME="localhost"
-    fi
+    GVM_CERTIFICATE_HOSTNAME=$(hostname --fqdn 2> /dev/null) || GVM_CERTIFICATE_HOSTNAME="localhost"
   fi
 
   # Certificate Authority (CA) Certificate Parameters
@@ -232,8 +228,7 @@ set_up_directories ()
 
   if [ ! -d "$GVM_CERT_LOCATION" ]
   then
-    mkdir -p "$GVM_CERT_LOCATION"
-    if [ $? -ne 0 ]
+    if ! mkdir -p "$GVM_CERT_LOCATION"
     then
       log_err "ERROR: Failed to create certificate directory ($GVM_CERT_LOCATION). Aborting."
       exit 1
@@ -242,8 +237,7 @@ set_up_directories ()
 
   if [ ! -d "$GVM_KEY_LOCATION" ]
   then
-    mkdir -p "$GVM_KEY_LOCATION"
-    if [ $? -ne 0 ]
+    if ! mkdir -p "$GVM_KEY_LOCATION"
     then
       log_err "ERROR: Failed to create private key directory ($GVM_KEY_LOCATION). Aborting."
       exit 1
@@ -281,14 +275,12 @@ create_private_key ()
 
   # Create a private key
   certtool \
-    --generate-privkey $CERTTOOL_PRIVKEY_PARAM \
+    --generate-privkey "$CERTTOOL_PRIVKEY_PARAM" \
     --outfile "$1" \
-    >> "$CERTTOOL_LOGFILE" 2>&1
-  if [ $? -ne 0 ]
-  then
+    >> "$CERTTOOL_LOGFILE" 2>&1 || {
     log_err "ERROR: Failed to generate private key, see $CERTTOOL_LOGFILE for details. Aborting."
     exit 1
-  fi
+  }
 
   log_write "Generated private key in $1."
 }
@@ -300,16 +292,16 @@ add_san_settings ()
   do
     case "$i" in
     *.*.*.*)
-      echo "ip_address = \"$i\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "ip_address = \"$i\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     ;;
     http*)
-      echo "uri = \"$i\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "uri = \"$i\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     ;;
     *.*)
-      echo "dns_name = \"$i\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "dns_name = \"$i\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     ;;
     localhost )
-      echo "dns_name = \"localhost\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "dns_name = \"localhost\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     ;;
     *)
       log_verbose "Invalid formatting for SAN: $i"
@@ -328,105 +320,105 @@ create_certificate ()
   rm -f "$GVM_CERT_TEMPLATE_FILENAME"
 
   # Create template using parameters
-  if [ $CERTIFICATE_TYPE -eq $CA_CERTIFICATE ]
+  if [ "$CERTIFICATE_TYPE" -eq "$CA_CERTIFICATE" ]
   then
     if [ -n "$GVM_CA_CERTIFICATE_LIFETIME" ]
     then
-      echo "expiration_days = $GVM_CA_CERTIFICATE_LIFETIME" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "expiration_days = $GVM_CA_CERTIFICATE_LIFETIME" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_COUNTRY" ]
     then
-      echo "country = \"$GVM_CA_CERTIFICATE_COUNTRY\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "country = \"$GVM_CA_CERTIFICATE_COUNTRY\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_STATE" ]
     then
-      echo "state = \"$GVM_CA_CERTIFICATE_STATE\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "state = \"$GVM_CA_CERTIFICATE_STATE\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_LOCALITY" ]
     then
-      echo "locality = \"$GVM_CA_CERTIFICATE_LOCALITY\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "locality = \"$GVM_CA_CERTIFICATE_LOCALITY\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_ORG" ]
     then
-      echo "organization = \"$GVM_CA_CERTIFICATE_ORG\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "organization = \"$GVM_CA_CERTIFICATE_ORG\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_ORG_UNIT" ]
     then
-      echo "unit = \"$GVM_CA_CERTIFICATE_ORG_UNIT\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "unit = \"$GVM_CA_CERTIFICATE_ORG_UNIT\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_HOSTNAME" ]
     then
-      echo "cn = \"$GVM_CA_CERTIFICATE_HOSTNAME\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "cn = \"$GVM_CA_CERTIFICATE_HOSTNAME\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CA_CERTIFICATE_SAN" ]
     then
-      add_san_settings $GVM_CA_CERTIFICATE_SAN
+      add_san_settings "$GVM_CA_CERTIFICATE_SAN"
     fi
   else
     if [ -n "$GVM_CERTIFICATE_LIFETIME" ]
     then
-      echo "expiration_days = $GVM_CERTIFICATE_LIFETIME" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "expiration_days = $GVM_CERTIFICATE_LIFETIME" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_COUNTRY" ]
     then
-      echo "country = \"$GVM_CERTIFICATE_COUNTRY\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "country = \"$GVM_CERTIFICATE_COUNTRY\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_STATE" ]
     then
-      echo "state = \"$GVM_CERTIFICATE_STATE\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "state = \"$GVM_CERTIFICATE_STATE\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_LOCALITY" ]
     then
-      echo "locality = \"$GVM_CERTIFICATE_LOCALITY\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "locality = \"$GVM_CERTIFICATE_LOCALITY\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_ORG" ]
     then
-      echo "organization = \"$GVM_CERTIFICATE_ORG\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "organization = \"$GVM_CERTIFICATE_ORG\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_ORG_UNIT" ]
     then
-      echo "unit = \"$GVM_CERTIFICATE_ORG_UNIT\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "unit = \"$GVM_CERTIFICATE_ORG_UNIT\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_HOSTNAME" ]
     then
-      echo "cn = \"$GVM_CERTIFICATE_HOSTNAME\"" >> $GVM_CERT_TEMPLATE_FILENAME
+      echo "cn = \"$GVM_CERTIFICATE_HOSTNAME\"" >> "$GVM_CERT_TEMPLATE_FILENAME"
     fi
     if [ -n "$GVM_CERTIFICATE_SAN" ]
     then
-      add_san_settings $GVM_CERTIFICATE_SAN
+      add_san_settings "$GVM_CERTIFICATE_SAN"
     fi
   fi
 
   # Add key usage constraints if the certificate type is known
-  if [ $CERTIFICATE_TYPE -eq $CA_CERTIFICATE ]
+  if [ "$CERTIFICATE_TYPE" -eq "$CA_CERTIFICATE" ]
   then
-    echo "ca" >> $GVM_CERT_TEMPLATE_FILENAME
-    echo "cert_signing_key" >> $GVM_CERT_TEMPLATE_FILENAME
-    echo "crl_signing_key" >> $GVM_CERT_TEMPLATE_FILENAME
+    { echo "ca";
+      echo "cert_signing_key";
+      echo "crl_signing_key"; } >> "$GVM_CERT_TEMPLATE_FILENAME"
   fi
-  if [ $CERTIFICATE_TYPE -eq $SERVER_CERTIFICATE ]
+  if [ "$CERTIFICATE_TYPE" -eq "$SERVER_CERTIFICATE" ]
   then
     # This certificate will be used to encrypt data and sign data.
     # This is the keyEncipherment flag in RFC5280 terminology.
-    echo "encryption_key" >> $GVM_CERT_TEMPLATE_FILENAME
-    echo "signing_key" >> $GVM_CERT_TEMPLATE_FILENAME
-    echo "tls_www_server" >> $GVM_CERT_TEMPLATE_FILENAME
+    { echo "encryption_key";
+      echo "signing_key";
+      echo "tls_www_server"; } >> "$GVM_CERT_TEMPLATE_FILENAME"
   fi
-  if [ $CERTIFICATE_TYPE -eq $CLIENT_CERTIFICATE ]
+  if [ "$CERTIFICATE_TYPE" -eq "$CLIENT_CERTIFICATE" ]
   then
     # This certificate will be used to sign data.
     # This is the digitalSignature flag in RFC5280 terminology.
-    echo "signing_key" >> $GVM_CERT_TEMPLATE_FILENAME
-    echo "tls_www_client" >> $GVM_CERT_TEMPLATE_FILENAME
+    echo "signing_key" >> "$GVM_CERT_TEMPLATE_FILENAME"
+    echo "tls_www_client" >> "$GVM_CERT_TEMPLATE_FILENAME"
   fi
 
-  if [ $DEBUG -eq 1 ]
+  if [ "$DEBUG" -eq 1 ]
   then
     echo "DEBUG: Using the following template ($GVM_CERT_TEMPLATE_FILENAME):" >> "$CERTTOOL_LOGFILE"
-    cat $GVM_CERT_TEMPLATE_FILENAME >> "$CERTTOOL_LOGFILE"
+    cat "$GVM_CERT_TEMPLATE_FILENAME" >> "$CERTTOOL_LOGFILE"
   fi
 
-  if [ $CREATE_SELF_SIGNED -eq 1 ]
+  if [ "$CREATE_SELF_SIGNED" -eq 1 ]
   then
     # Create a self signed certificate
     log_verbose "  Generating self signed certificate."
@@ -436,12 +428,10 @@ create_certificate ()
       --load-privkey "$GVM_KEY_FILENAME" \
       --outfile "$GVM_CERT_FILENAME" \
       --template "$GVM_CERT_TEMPLATE_FILENAME" \
-      >> "$CERTTOOL_LOGFILE" 2>&1
-    if [ $? -ne 0 ]
-    then
+      >> "$CERTTOOL_LOGFILE" 2>&1 || {
       log_err "ERROR: Failed to create self signed certificate, see $CERTTOOL_LOGFILE for details. Aborting."
       exit 1
-    fi
+    }
 
     log_write "Generated self signed certificate in $GVM_CERT_FILENAME."
   else
@@ -452,12 +442,10 @@ create_certificate ()
       --load-privkey "$GVM_KEY_FILENAME" \
       --outfile "$GVM_CERT_REQUEST_FILENAME" \
       --template "$GVM_CERT_TEMPLATE_FILENAME" \
-      >> "$CERTTOOL_LOGFILE" 2>&1
-    if [ $? -ne 0 ]
-    then
-      log_err "ERROR: Failed to create certificate request, see $CERTTOOL_LOGFILE for details. Aborting."
-      exit 1
-    fi
+      >> "$CERTTOOL_LOGFILE" 2>&1 || {
+        log_err "ERROR: Failed to create certificate request, see $CERTTOOL_LOGFILE for details. Aborting."
+        exit 1
+      }
 
     log_write "Generated certificate request in $GVM_CERT_REQUEST_FILENAME."
   fi
@@ -491,12 +479,10 @@ sign_certificate ()
     --outfile "$GVM_CERT_FILENAME" \
     --load-ca-certificate "$GVM_SIGNING_CA_CERT_FILENAME" \
     --load-ca-privkey "$GVM_SIGNING_CA_KEY_FILENAME" \
-    --template "$GVM_CERT_TEMPLATE_FILENAME" >> "$CERTTOOL_LOGFILE" 2>&1
-  if [ $? -ne 0 ]
-  then
-    log_err "ERROR: Failed to sign certificate, see $CERTTOOL_LOGFILE for details. Aborting."
-    exit 1
-  fi
+    --template "$GVM_CERT_TEMPLATE_FILENAME" >> "$CERTTOOL_LOGFILE" 2>&1 || {
+      log_err "ERROR: Failed to sign certificate, see $CERTTOOL_LOGFILE for details. Aborting."
+      exit 1
+    }
 
   log_write "Signed certificate request in $GVM_CERT_REQUEST_FILENAME with CA certificate in $GVM_SIGNING_CA_CERT_FILENAME to generate certificate in $GVM_CERT_FILENAME"
 }
@@ -527,14 +513,13 @@ install_cert ()
   fi
 
   KEY_INSTALL="$GVM_KEY_LOCATION/${1}key.pem"
-  if [ -f "$KEY_INSTALL" ] && [ $FORCE -ne 1 ]
+  if [ -f "$KEY_INSTALL" ] && [ "$FORCE" -ne 1 ]
   then
     echo "$KEY_INSTALL exists already, not overwriting."
     echo "Use '-f' parameter to overwrite existing files."
     exit 1
   else
-    cp "$GVM_KEY_FILENAME" "$KEY_INSTALL"
-    if [ $? -ne 0 ]
+    if ! cp "$GVM_KEY_FILENAME" "$KEY_INSTALL"
     then
       log_err "Failed to install $GVM_KEY_FILENAME to $KEY_INSTALL.  Aborting."
       exit 1
@@ -544,14 +529,13 @@ install_cert ()
   fi
 
   CERT_INSTALL="$GVM_CERT_LOCATION/${1}cert.pem"
-  if [ -f "$CERT_INSTALL" ] && [ $FORCE -ne 1 ]
+  if [ -f "$CERT_INSTALL" ] && [ "$FORCE" -ne 1 ]
   then
     echo "$CERT_INSTALL exists already, not overwriting."
     echo "Use '-f' parameter to overwrite existing files."
     exit 1
   else
-    cp "$GVM_CERT_FILENAME" "$CERT_INSTALL"
-    if [ $? -ne 0 ]
+    if ! cp "$GVM_CERT_FILENAME" "$CERT_INSTALL"
     then
       log_err "Failed to install $GVM_CERT_FILENAME to $CERT_INSTALL.  Aborting."
       exit 1
@@ -596,12 +580,11 @@ verify ()
 
   # TODO: Check file permissions
 
-  certtool \
+  if certtool \
     --verify \
-    --load-ca-certificate $GVM_CERT_LOCATION/cacert.pem \
-    --infile $GVM_CERT_LOCATION/cacert.pem \
+    --load-ca-certificate "$GVM_CERT_LOCATION"/cacert.pem \
+    --infile "$GVM_CERT_LOCATION"/cacert.pem \
     >> "$CERTTOOL_LOGFILE" 2>&1
-  if [ $? -eq 0 ]
   then
     echo "OK: CA certificate verified."
   else
@@ -609,24 +592,25 @@ verify ()
     ALL_OK=0
   fi
 
-  for cert in $(find $GVM_CERT_LOCATION -name "*pem" ! -name cacert.pem)
+  find "$GVM_CERT_LOCATION" -name "*pem" ! -name cacert.pem > tmp
+  while IFS= read -r cert
   do
-    certtool \
+    if certtool \
       --verify \
-      --load-ca-certificate $GVM_CERT_LOCATION/cacert.pem \
-      --infile $cert \
+      --load-ca-certificate "$GVM_CERT_LOCATION"/cacert.pem \
+      --infile "$cert" \
       >> "$CERTTOOL_LOGFILE" 2>&1
-    if [ $? -eq 0 ]
     then
       echo "OK: Certificate $cert verified."
     else
       echo "ERROR: Certificate $cert failed verification, see $CERTTOOL_LOGFILE for details. Aborting."
-    ALL_OK=0
+      ALL_OK=0
     fi
-  done
+  done < tmp
+  rm tmp
 
   echo
-  if [ $ALL_OK -eq 1 ]
+  if [ "$ALL_OK" -eq 1 ]
   then
     echo "OK: Your GVM certificate infrastructure passed validation."
   else
@@ -644,10 +628,10 @@ clean_up ()
 {
   if [ $USE_TEMP_DIR -eq 1 ]
   then
-    if [ $DEBUG -ne 1 ]
+    if [ "$DEBUG" -ne 1 ]
     then
       log_write "Removing temporary directory $GVM_CERT_DIR."
-      rm -rf $GVM_CERT_DIR
+      rm -rf "$GVM_CERT_DIR"
     else
       echo "DEBUG: Not removing $GVM_CERT_DIR in debug mode."
     fi
@@ -667,8 +651,8 @@ INSTALL_CA=0
 CREATE_CERTIFICATE=0
 CREATE_SELF_SIGNED=0
 CERTIFICATE_TYPE=0
-CREATE_SERVER_CERTIFICATE=0
-CREATE_CLIENT_CERTIFICATE=0
+export CREATE_SERVER_CERTIFICATE=0
+export CREATE_CLIENT_CERTIFICATE=0
 CREATE_CSR=0
 CREATE_CA=0
 SIGN_CERTIFICATE=0
@@ -752,6 +736,7 @@ then
   if [ -r "$CONFIGURATION_FILE" ]
   then
     log_verbose "Reading configuration from $CONFIGURATION_FILE."
+    # shellcheck source=/dev/null
     . "$CONFIGURATION_FILE"
   else
     log_err "Configuration file $CONFIGURATION_FILE could not be read. Aborting."
