Add functions to synchronize SCAP database with user defined OVAL 	repositories in private subdirectory.
	* CMakeLists.txt: Add oval_verify.xsl, ovaldef_list_ids.xsl.

	* tools/openvas-scapdata-sync.in (do_help): Add --refresh-private text.
	(init_sec_db_update): New function, contains database checks and
	variable inits from update_sec_db.
	(list_oval_files_sorted, list_oval_files_sortable): Change to search
	directory given as parameter instead of fixed directory and skip files
	without valid OVAL timestamp.
	(update_sec_db_private): New function to sync scap.db with user defined
	files. Currently supports validating, adding and removing OVAL
	definitions.
	(update_sec_db): Remove database checks and variable inits, call
	init_sec_db_update instead. Change handling of OVAL files list to new
	version of list_oval_files_sorted and print warnings for file without
	valid timestamps. Add call of update_sec_db_private near end.
	(do_refresh_private): New function to refresh user defined data only.
	(): New command line option --refresh-private.

	* tools/ovaldef_list_ids.xsl: New stylesheet to get a list of all IDs
	in an OVAL repository.

	* tools/oval_timestamp, tools/oval_update.xsl: Fix selection of
	timestamps failing when relevant elements contain extra whitespaces.

	* tools/oval_verify.xsl: New stylesheet for basic verification of OVAL
	repository files.


git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-manager@15611 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/openvas-scapdata-sync.in b/tools/openvas-scapdata-sync.in
--- a/tools/openvas-scapdata-sync.in
+++ b/tools/openvas-scapdata-sync.in
@@ -96,6 +96,7 @@ do_help () {
   echo "$0: Sync SCAP data using different protocols"
   echo " --rsync		sync with rsync (default)"
   echo " --refresh		update database without downloading feed data"
+  echo " --refresh-private	update database only using private data"
   echo " --check		just checksum check"
   echo "OpenVAS administrator functions:"
   echo " --selftest	perform self-test"
@@ -245,21 +246,7 @@ check_db_version () {
   esac
 }
 
-list_oval_files_sorted () {
-for line in `list_oval_files_sortable | sort`
-  do
-    echo ${line#????????}
-  done
-}
-
-list_oval_files_sortable () {
-for ovalfile in `find "$SCAP_DIR/oval/" -name "*.xml" -type f`
-  do
-    echo `xsltproc "$SCAP_RES_DIR/oval_timestamp.xsl" "$ovalfile" | sed -e 's/T.*//' | tr -d "-"`"$ovalfile"
-  done
-}
-
-update_sec_db () {
+init_sec_db_update () {
   if [ ! -f $SEC_DB ]
   then
     echo "[i] Initializing scap database"
@@ -289,6 +276,165 @@ update_sec_db () {
     OVAL_REFDATE=0
     DB_LASTUPDATE=0
   fi
+}
+
+list_oval_files_sorted () {
+for line in `list_oval_files_sortable "$1" | sort`
+  do
+    echo ${line#????????}
+  done
+}
+
+list_oval_files_sortable () {
+for ovalfile in `find "$1" -name "*.xml" -type f`
+  do
+    timestamp_raw=""
+    timestamp_raw=`xsltproc "$SCAP_RES_DIR/oval_timestamp.xsl" "$ovalfile" 2>/dev/null`
+
+    if [ -n "$timestamp_raw" ] \
+       && [ -n `echo "$timestamp_raw" | egrep -x "[0-9]{4}\-(0[0-9]|1[012])\-([0-2][0-9]|3[01])[:alnum:]*"` ]
+    then
+      timestamp="`echo "$timestamp_raw" | sed -e 's/T.*//' | tr -d "-"`"
+      echo "$timestamp$ovalfile"
+    fi
+  done
+}
+
+update_sec_db_private () {
+  SCAP_PRIVATE_DIR="$SCAP_DIR/$PRIVATE_SUBDIR"
+  if [ -d "$SCAP_PRIVATE_DIR" ]
+  then
+    echo "[i] Updating user defined data"
+
+    echo "[i] Updating user OVAL definitions"
+    xmlcount=0
+    xmlcount=$(find "$SCAP_PRIVATE_DIR/oval/" -name "*.xml" -type f 2> /dev/null | wc -l)
+    if [ -n "$xmlcount" ] && [ $xmlcount -ne 0 ]
+    then
+      if [ -z "$oval_files_sorted" ]
+      then
+        oval_files_sorted=`list_oval_files_sorted "$SCAP_DIR/oval/"`
+        ovaldir_xml_files=`find "$SCAP_DIR/oval/" -name "*.xml" -type f 2> /dev/null`
+
+        for xml_file in $ovaldir_xml_files
+        do
+          if [ -z `echo "$oval_files_sorted" | grep -x "$xml_file"` ]
+          then
+            echo "[w] Cannot find valid OVAL timestamp in '$xml_file'."
+          fi
+        done
+      fi
+
+      oval_files_sorted_private=`list_oval_files_sorted "$SCAP_PRIVATE_DIR/oval/"`
+      ovaldir_xml_files=`find "$SCAP_PRIVATE_DIR/oval/" -name "*.xml" -type f 2> /dev/null`
+
+      for xml_file in $ovaldir_xml_files
+      do
+        if [ -z `echo "$oval_files_sorted_private" | grep -x "$xml_file"` ]
+        then
+          echo "[w] Cannot find valid OVAL timestamp in '$xml_file'."
+        fi
+      done
+
+      for non_xml_file in `find "$SCAP_PRIVATE_DIR/oval/" -type f -and -not -name "*.xml" 2> /dev/null`
+      do
+        if [ "${non_xml_file%%.asc}" = "${non_xml_file}" ] || ! [ -f "${non_xml_file%%.asc}" ]
+        then
+          echo "[w] Found non-XML and non-signature file '$non_xml_file'."
+        fi
+      done
+
+      if [ -n "$oval_files_sorted" ]
+      then
+        for ovalfile in $oval_files_sorted_private
+        do
+          if [ `stat -c "%Y" "$ovalfile" | cut -d " " -f 1 | tr -d "-"` -ge $DB_LASTUPDATE ]
+          then
+            oval_timestamp=`xsltproc "$SCAP_RES_DIR/oval_timestamp.xsl" "$ovalfile" | sed -e 's/T.*//' | tr -d "-"`
+
+            OVAL_REFDATE=`$SQLITE $SEC_DB "SELECT date(max(modification_time),'unixepoch') FROM ovaldefs WHERE xml_file = '${ovalfile##$SCAP_DIR/}';" | tr -d "-"`
+            if [ -z "$OVAL_REFDATE" ]
+            then
+              OVAL_REFDATE=0
+            fi
+
+            if [ $oval_timestamp -ge $OVAL_REFDATE ]
+            then
+              validation_message=`xsltproc "$SCAP_RES_DIR/oval_verify.xsl" "$ovalfile" 2>/dev/null`
+              validation_return="$?"
+              if [ 0 -ne $validation_return ] && [ -n "$validation_message" ]
+              then
+                if [ 10 -eq $validation_return ]
+                then
+                  echo "[w] Validation of file '$ovalfile' failed: $validation_message"
+                else
+                  echo "[w] Error parsing '$ovalfile'."
+                fi
+              else
+                if ! [ "$validation_message" = "file valid" ]
+                then
+                  echo "[w] Validation of file '$ovalfile' failed: $validation_message"
+                else
+                  found_duplicates=0
+                  for feedfile in $oval_files_sorted
+                  do
+                    compare=`xsltproc "$SCAP_RES_DIR/ovaldef_list_ids.xsl" "$ovalfile"`
+                    duplicates=`xsltproc "$SCAP_RES_DIR/ovaldef_list_ids.xsl" "$feedfile" | grep -Fxc "$compare"`
+                    if [ 0 -lt $duplicates ]
+                    then
+                      echo "[w] Skipping '$ovalfile', found $duplicates definition(s) that are duplicates of one(s) in '$feedfile'"
+                      found_duplicates=1
+                    fi
+                  done
+                  if [ 0 -eq $found_duplicates ]
+                  then
+                    echo "[i] Updating '$ovalfile'"
+                    xsltproc --stringparam filename "${ovalfile##$SCAP_DIR/}" --stringparam refdate "$OVAL_REFDATE" "$SCAP_RES_DIR/oval_update.xsl" "$ovalfile" | \
+                    $SQLITE $SEC_DB
+                  fi
+                fi
+              fi
+            else
+              echo "[i] Skipping $ovalfile, file has older timestamp than latest OVAL definition in database."
+            fi
+          else
+            echo "[i] Skipping $ovalfile, file is older than last revision."
+          fi
+        done
+      fi
+    else
+      echo "[i] No user defined OVAL files found"
+    fi
+
+    echo "[i] Cleaning up user OVAL data"
+    DIR_STR_LENGTH=$((`echo "$SCAP_DIR" | wc -c` + 1))
+
+    oval_files_shortened=""
+    if [ 0 != "$xmlcount" ]
+    then
+      for ovalfile in $oval_files_sorted_private
+      do
+        oval_files_shortened=$oval_files_shortened"', '"`echo $ovalfile | cut -c ${DIR_STR_LENGTH}- `
+      done
+      oval_files_shortened=${oval_files_shortened##"', "}"'"
+    fi
+
+    deleted=`$SQLITE "$SEC_DB" "SELECT DISTINCT xml_file FROM ovaldefs WHERE (xml_file NOT LIKE 'oval/%') AND (xml_file NOT IN ($oval_files_shortened));"`
+    if [ -n "$deleted" ]
+    then
+      echo "[i] Removing definitions formerly inserted from:"
+      echo "$deleted"
+      $SQLITE "$SEC_DB" "DELETE FROM ovaldefs WHERE (xml_file NOT LIKE 'oval/%') AND (xml_file NOT IN ($oval_files_shortened));"
+    fi
+
+    $SQLITE $SEC_DB "update meta set value ='`date +%s`' where name = 'last_update';"
+  else
+    echo "[i] No user data directory '$SCAP_PRIVATE_DIR' found."
+  fi
+}
+
+update_sec_db () {
+  init_sec_db_update
 
   CPEBASE="$SCAP_DIR/official-cpe-dictionary_v2.2.xml"
   if [ -e $CPEBASE ]
@@ -303,7 +449,7 @@ update_sec_db () {
     else
       echo "[i] Skipping CPEs, file is older than last revision"
     fi
-  else  
+  else
     echo "[w] No CPE dictionary found in $SCAP_DIR"
   fi
 
@@ -360,7 +506,19 @@ update_sec_db () {
   xmlcount=$(find "$SCAP_DIR/oval/" -name "*.xml" -type f 2> /dev/null | wc -l)
   if [ $xmlcount -ne 0 ]
   then
-    for ovalfile in `list_oval_files_sorted`
+
+    oval_files_sorted=`list_oval_files_sorted "$SCAP_DIR/oval/"`
+    ovaldir_xml_files=`find "$SCAP_DIR/oval/" -name "*.xml" -type f 2> /dev/null`
+
+    for xml_file in $ovaldir_xml_files
+    do
+      if [ -z `echo "$oval_files_sorted" | grep -x "$xml_file"` ]
+      then
+        echo "[w] Cannot find valid OVAL timestamp in '$xml_file'."
+      fi
+    done
+
+    for ovalfile in $oval_files_sorted
     do
       if [ `stat -c "%Y" "$ovalfile" | cut -d " " -f 1 | tr -d "-"` -ge $DB_LASTUPDATE ]
       then
@@ -388,12 +546,19 @@ update_sec_db () {
     echo "[w] No XML files found in $SCAP_DIR/oval/."
   fi
 
+  update_sec_db_private
+
   $SQLITE $SEC_DB "update meta set value ='`date +%s`' where name = 'last_update';"
 }
 
 do_refresh () {
   echo "[i] Refreshing database without feed sync."
   update_sec_db
+}
+
+do_refresh_private () {
+  init_sec_db_update
+  update_sec_db_private
 }
 
 if [ -n "$1" ]; then
@@ -417,6 +582,10 @@ if [ -n "$1" ]; then
         ;;
       --refresh)
         do_refresh
+        exit 0
+        ;;
+      --refresh-private)
+        do_refresh_private
         exit 0
         ;;
       --check)
